### ISSUE TITLE
parseCookies is not working on Cookies on the client 

### ISSUE THREAD

**Issue by anehkumar** [maticzav/nookies#124]
Hi, I try to load cookie in componentDidMount but when I refresh the page I get cookie inside getInitialProps function I don't know how to fix this.

```
const cookies = parseCookies();
 console.log({ cookies })
```
It was return empty data, Please help

**Comment by ImJacobChen** [comment]
console.log(cookies); ?

**Comment by maticzav** [comment]
Could you share a bit more details about your case? A reproduction repository would be great.

**Comment by siebigteroth** [comment]
Same for getting a cookies.
`
import nookies from 'nookies';
console.log(nookies.get());
`
Returns `{}`. Even if I provide an empty {} object as NextContext-paramter as described in the documentation.

**Comment by maticzav** [comment]
@siebigteroth where are you running the parser?

**Comment by siebigteroth** [comment]
@maticzav On SSR it's working fine. It's not working via CSR it's empty.
In my case, the code where I use nookies is part of a package, that is used in a next-application.
To build this package, I run `tsc && tsc -d --emitDeclarationOnly --declarationDir dist --allowJs false` to parse my typescript code.

**Comment by maticzav** [comment]
@siebigteroth what I was referring to is which part of the page (i.e. the getInitialProps method, render, or something else). I am interested in that because of the underlying functionality (https://github.com/maticzav/nookies/blob/b535340452ae727838ce8d261d5cbca44cf383b7/src/index.ts#L57)

**Comment by siebigteroth** [comment]
@maticzav I use the get/ parseCookie method in different parts of my application.
The parts under getInitialProps for SSR are running fine. But e.g. in useEffect-parts, where the context isn't provided, and is run via CSR, the get/ parseCookie method returns `{}`. Even if the part under getInitialProps, which is executed before useEffect, returned cookies.

**Comment by maticzav** [comment]
@siebigteroth let me know if I can help. If you could compose a small reproduction repository that would be perfect 🙂

**Comment by siebigteroth** [comment]
@maticzav I could figure it out. Some other component in the application manipulated the cookie, which caused the difference between csr and ssr.
So nookies working as expected, even after severall stress-tests :-)

@anehkumar Maybe there is a similar problem in your application. Just ensure, that document.cookie return the expected value.
`console.log(typeof document !== 'undefined' ? document.cookie : 'no cookies, ssr')`

**Comment by maticzav** [comment]
Awesome! Glad to hear that it's working. 🙂
