### ISSUE TITLE
ctx.req.hostname is only available when using a custom server

### ISSUE THREAD

**Issue by grsmvg** [maticzav/nookies#137]
This plugin breaks on Next 9, when using the default next (dev) server, because nookies tries to read ctx.req.hostname. It should read ctx.req.headers.host.

See also: https://spectrum.chat/next-js/general/ctx-req-hostname-removed~c246de06-2898-4785-8f9c-38c22cc2d983

**Comment by grsmvg** [comment]
Nvm, tried to PR this issue but found out hostname is not used at all in the source code of nookie. Followed the stack trace wrongly 🤦‍♂️

**Comment by maticzav** [comment]
@grsmvg no worries! Let me know if you need any help whatsoever. 🙂
