### ISSUE TITLE
Overwrite cookie with the same options and name

### ISSUE THREAD

**Issue by koprivajakub** [maticzav/nookies#15]
I am facing an issue, where I call the `setCookie` multiple times in a row on server with same cookie name and options but different values. This might not be a problem because the browser should take the latest which is valid but to be sure I would like to send a cookie only once.

**Comment by koprivajakub** [comment]
So the code to reproduce is for example:

```
setCookie(ctx, "cookieName", "cookieValue", {
  path: "/",
  maxAge: 60 * 60 * 24 * 365
});
setCookie(ctx, "cookieName", "cookieValue2", {
  path: "/",
  maxAge: 60 * 60 * 24 * 365
});
```

The response headers contain:
```
"Set-Cookie": cookieName=cookieValue; Expires=...
"Set-Cookie": cookieName=cookieValue2; Expires=...
```

and so on.
I have created PR #16 that should fix this, also I am willing to add some test for it but I have not found any tests at all in the repository. So that is open to discussion what framework you want to use I am familiar with mocha and chai for assertions.

**Comment by koprivajakub** [comment]
@maticzav are you still maintaining the repository? The PR issue and PR is here for more than two weeks. So I am just asking if there is any feedback from your side or I should reconsider the usage of nookies in my project?

**Comment by maticzav** [comment]
Hey @koprivajakub 👋,

I am so sorry for the late reply. Thank you for being so patient! I just pushed the new version with many improvements and changes. Could you align the PR with that? I would be more than happy to merge it afterwards. 🙂

**Comment by koprivajakub** [comment]
@maticzav Thank you for introducing TS, The PR has been updated and I think it is ready for merge. Please lets start a thread in there in case of any comments for the code. 👍
