### ISSUE TITLE
Issue with destroyCookie in 1.2.0

### ISSUE THREAD

**Issue by vaunus** [maticzav/nookies#17]
I'm having problems with the destroyCookie method not removing the cookie in v1.2.0. It looks like it's because of the domain and path options not being passed through correctly as I am setting these explicitly when I create the cookie. 

I noticed you had added an options parameter for destroyCookie recently but I can't see this in the npm module import. If I copy and paste the destroyCookie method directly into my codebase and use it that way it seems to work as expected.

**Comment by VahediRepositories** [comment]
I'm using version 2.2.1 and destroyCookie(null, name) acts differently on different situations.
It always works fine except for when the page is loaded using Router.push(). when the page is loaded using Router.push, sometimes it doesn't work!

So I passed it the path and now it works fine in all situations.
