### ISSUE TITLE
`options` parameter not specified in `destroyCookie` doc

### ISSUE THREAD

**Issue by lcswillems** [maticzav/nookies#184]
I wanted to destroy a cookie called `authToken`, on client side. According to the documentation, I used:

```
destroyCookie(undefined, 'authToken');
```

But it wasn't working. After looking to the source code, I found that I wasn't specifying the good options ([but the doc doesn't mention the `options`](https://github.com/maticzav/nookies#destroycookiectx-name-or-cookiesdestroyctx-token)).

**Comment by damien-monni** [comment]
Same for me, it wasn't destroyed because I wasn't using domain and path options.

**Comment by fabioruolo** [comment]
there you go: https://github.com/maticzav/nookies/pull/201
