### ISSUE TITLE
httpOnly option is misleading

### ISSUE THREAD

**Issue by vassbence** [maticzav/nookies#207]
Hi!

AFAIK there is no way in JS to create a httpOnly cookie, but the docs show httpOnly as an option.

**Comment by maticzav** [comment]
Hi!

All cookie options are derived from dependency library `cookie`.

**Comment by vassbence** [comment]
I see, but an error should be thrown if someone tries to set a httpOnly cookie on client side with `setCookie`.

**Comment by maticzav** [comment]
I could merge a PR if you are up for it

**Comment by ibrhm-mnf-fingent** [comment]
Still getting an error if httpOnly option not added when setting a cookie
<img width="1728" alt="a325e7ef7ba04c44360b616c8b2266bb-screen-shot-2020-03-30-at-15-59-18" src="https://user-images.githubusercontent.com/58180892/78001837-e7672d80-7353-11ea-9de0-d7c162c5da36.png">

**Comment by maticzav** [comment]
try with the next version - the problem was that option was required now - using `{}` would probably also solve the problem

**Comment by Felipe-Tomazetti** [comment]
I am trying to use httpOnly as true like this
` setCookie(undefined, 'token', response.data.token, {
          httpOnly: true,
          secure: true,
          maxAge: 60 * 60 * 24, //1 day
        });`

But the token is not being saved to the APplication cookies on the browser, am I doing something wrong?
