### ISSUE TITLE
Allow to create cookie without providing ctx for client-side

### ISSUE THREAD

**Issue by BjoernRave** [maticzav/nookies#216]
I would like to be able to set a cookie on the client-side where I don't need to provide the ctx

**Comment by kovalyovkirill** [comment]
I think, you can do this, just don't pass context:
```javascript
setCookie(, 'token', token, {
      maxAge: 30 * 24 * 60 * 60,
      path: '/',
})
```

**Comment by jon301** [comment]
@kovalyovkirill 

![image](https://user-images.githubusercontent.com/122108/74978587-33f24b80-542d-11ea-9660-7eff8ffcd024.png)

It looks like passing an empty string as context works, but it feels a bit hacky:

```
setCookie('', 'token', token, {
      maxAge: 30 * 24 * 60 * 60,
      path: '/',
})```
