### ISSUE TITLE
Is it possible to set a cookie on a serverless function in Next?

### ISSUE THREAD

**Issue by mirshko** [maticzav/nookies#249]
for some reason this isn't creating the cookie?

<img width="381" alt="Screen Shot 2020-04-03 at 17 30 24" src="https://user-images.githubusercontent.com/8116716/78378111-ceb77b80-75d0-11ea-84b1-60502c28d27b.png">

**Comment by maticzav** [comment]
Could you show the entire function?

**Comment by mirshko** [comment]
```js
export default async (req, res) => {
  try {
    const { email, password } = JSON.parse(req.body);

    const session = await login(email, password);

    res.status(200).json(session);
  } catch (err) {
    console.error(err);

    res.status(401).json({
      error: err.message,
    });
  }
};
```

**Comment by mirshko** [comment]
@maticzav any help here?

**Comment by maticzav** [comment]
@mirshko I am sorry, I am not sure I know the answer. Perhaps someone from community could help if they spot the issue.

**Comment by leosuncin** [comment]
`res` needs to be wrapped with curly braces

```javascript
setCookie({ res }, 'token', token, {
  httpOnly: true,
  path: '/',
  sameSite: 'strict',
});
```

**Comment by mirshko** [comment]
oh shit! that makes sense as it’s not the whole response context object! 

let me test this! thanks!

**Comment by andrewmartin** [comment]
Hi there, I'm having the exact same issue here. I'm using more or less the exact same sample code. Wrapping in the `{ req }` didn't seem to work.

It's odd because it actually does save it (when I log out the `res.cookies` I see it). But it doesn't persist in the browser.

```ts
const handler = (req: NextApiRequest, res: NextApiResponse) => {
  const { token } = req.body

  nookies.set({ res }, 'fromServer', 'value', {
    maxAge: 30 * 24 * 60 * 60,
    path: '/page',
  })

  // Return the `set-cookie` header so we can display it in the browser and show that it works!
  res.send({
    token: res.getHeader('Set-Cookie'), // strangely, I'm seeing it in the output here!
  })
}
```

Any thoughts? I'm going to try the suggestion here in the meantime. https://github.com/maticzav/nookies/issues/249#issuecomment-608996207

**Comment by andrewmartin** [comment]
My apologies, I fat-fingered the paste:

```
path: '/page'
```

Looks like this is working great. Thanks much and sorry to bug!
