### ISSUE TITLE
Update docs in favor of getStaticProps and getServerSideProps

### ISSUE THREAD

**Issue by Gabsii** [maticzav/nookies#290]
Since NextJS 9.3 the docs recommend using `getStaticProps` and `getServerSideProps` over `getInitialProps`. 
In this package's docs `getInitialProps` is still being used, is there a particular reason to stick with `getInitialProps` for the time being?

**Comment by maticzav** [comment]
No particular reason - didn't manage to update yet. If you find some spare time to contribute to the README, I would be delighted to merge the pull request.
