### ISSUE TITLE
Does it support a custom server?

### ISSUE THREAD

**Issue by omar-dulaimi** [maticzav/nookies#314]
Hello, thanks for the awesome library.
Since we use a custom server for our routes, I wanted to use the same library to handle cookies everywhere on the stack/project.
So does this library support this use case? A custom Express server?

Any future plans?

**Comment by maticzav** [comment]
Hey @omar-dulaimi :wave:, That's an interesting question. 

Right now, I don't have the capacity to work on it anytime soon. On the other hand, it sounds soo cool. I'd be thrilled to merge a PR with such functionality.

**Comment by omar-dulaimi** [comment]
Hello @maticzav 
I'd love to make such a contribution to the open source, I'll take a look at the code and see what I can do.
But I hope there won't be any rush because this is my first ever contribution :)

**Comment by omar-dulaimi** [comment]
Thank you for the great developer experience :)

**Comment by maticzav** [comment]
Thank you for the PR! 🚀
