### ISSUE TITLE
cookie destory fails on the client side

### ISSUE THREAD

**Issue by abhijithvijayan** [maticzav/nookies#318]
This is a weird behaviour I observed with `next.js 9.5.1`.
Destroying the cookie on the client side(with `destroyCookie(null, 'cookieName')`) fails(nothing happens) when using a custom express server.

But as in your https://github.com/maticzav/nookies/issues/133#issuecomment-513707606 , using `getInitialProps` doesn't work either.

Create a `logout` route and use `getInitialProps` to carry out cookie removal.

```
LogoutPage.getInitialProps = async (appContext) => {
  destroyCookie(appContext.ctx, 'token');

  // https://err.sh/vercel/next.js/empty-object-getInitialProps
  return {logout: true};
};
```

Also, thanks for this awesome library, made my day :100:

**Comment by abhijithvijayan** [comment]
Update:

I ended up doing

```
enum Cookie {
  TOKEN = 'token',
  PATH = '/',
}

export function removeToken() {
  return (document.cookie = `${Cookie.TOKEN}=; Path=${Cookie.PATH}; Expires=Thu, 01 Jan 1970 00:00:01 GMT;`);
}
```

**Comment by maticzav** [comment]
Hey @abhijithvijayan  👋 ,

Is this resolved then?

**Comment by abhijithvijayan** [comment]
Yeah but using this library didnt help.

**Comment by kaushal-enstead** [comment]
```
nookies.set(null, key, value, { maxAge, path: '/' });
```

```
nookies.destroy(null, key, { path: '/' });
```

For me i was missinf path property
