### ISSUE TITLE
express is not includes as one of the dependencies

### ISSUE THREAD

**Issue by louiskhenghao** [maticzav/nookies#344]
There is an error saying `express` is not defined when I included this package as one of my dependencies for some open source project...
I realized there is only `@types/express` is defined in `devDependencies` but `express` is not included in `dependencies`

**Comment by maticzav** [comment]
Hey 👋 ,

Thank you for opening the issue. We only list types dependency because we use none of express's functionality. Could you provide small reproduction CodeSandbox for your issue?

**Comment by louiskhenghao** [comment]
hey, so sorry for the late reply.... I've resolved this issue by fork of this repo and modified it
But I will provide some screenshots in the next few days time since the original source was my initial thoughts.
thank you once again

**Comment by maticzav** [comment]
Awesome! Could you open a PR with the fix?
