### ISSUE TITLE
Setting multiple cookies in SSR should not re-encode with encodeURIComponent

### ISSUE THREAD

**Issue by mkteh95** [maticzav/nookies#352]
### Problem
During SSR, if we've called `setCookie` before with a `custom encode` function, setting another cookie re-encodes the value of the previous cookie using `encodeURIComponent`.

Here's the relevant snippet.
https://github.com/maticzav/nookies/blob/2829f4964c5722eeddc7562d5834d51c324af0ac/src/index.ts#L132-L140

Looking at `Line 136`, we can see that we do not pass an `encode` function. This results in the previously-set cookies being `encoded` using the default `encodeURIComponent`. I believe we should pass an encode function like: `(val) => val` so it retains its current encoding. It is the responsibility of developers to ensure they use proper encoding should they pass a custom `encode` function.

### Reproduction
1. Call `setCookie(ctx, 'key1', '|', { encode: (val) => val })` in `SSR`.
2. Call `setCookie(ctx, 'key2', '|', { encode: (val) => val })` in `SSR`.
3. Value of `key1` becomes `%7C`.

### Solution
```ts
    parsedCookies.forEach((parsedCookie: Cookie) => {
      if (!areCookiesEqual(parsedCookie, createCookie(name, value, options))) {
        cookiesToSet.push(
          cookie.serialize(parsedCookie.name, parsedCookie.value, {
            encode: (val: string) => val, // Use a pass-through function for encode
            ...(parsedCookie as cookie.CookieSerializeOptions),
          }),
        )
      }
    })
```

**PR** demonstrating proposed fix: https://github.com/maticzav/nookies/pull/357

Lemme know if there are concerns with the suggested changes.

**Comment by maticzav** [comment]
:wave: I think we've resolved this, right? Please do reopen if I made a mistake. Thank you again for helping ❤️

**Comment by mkteh95** [comment]
Oops just saw this 😅 Yes its resolved. Thanks for releasing the fix.
