### ISSUE TITLE
What is maxAge

### ISSUE THREAD

**Issue by adamgajzlerowicz** [maticzav/nookies#43]
Hi, What is expected time measure unit in maxAge argument? I am trying to set cookie to expire in 5 minutes, having some hard time with this. Can you provide any inside please? It could be helpful to add it to the docs probably

Thanks!

**Comment by jericopulvera** [comment]
The answer could be found here.

https://github.com/jshttp/cookie#maxage

https://github.com/jshttp/cookie#expires
