### ISSUE TITLE
how to get cookie on server

### ISSUE THREAD

**Issue by urmauur** [maticzav/nookies#44]
Hi guys, i need read cookie and do some action from redux, i try this one for set cookie when undifined and success create `cookie`, and how if the cookie already on browser and value `true` ?

```js
static async getInitialProps({ Component, ctx }) {
    // Parse cookies
    const cookies = nookies.get(ctx);

    if (cookies.theme === undefined || cookies.theme === false) {
      ctx.store.dispatch(changeTheme(false));
      nookies.set(ctx, 'theme', false);
    }

    else if (cookies.theme === true ) {
      ctx.store.dispatch(changeTheme(true));
      nookies.set(ctx, 'theme', true);
    }

    return {
      pageProps: {
        // Call page-level getInitialProps
        ...(Component.getInitialProps ? await Component.getInitialProps(ctx) : {})
      },
      cookies
    };
  }
```

**Comment by maticzav** [comment]
Hey 👋, could you elaborate on what your question is? I am not sure I understand it entirely.

**Comment by talkaboutdesign** [comment]
I think he is asking how to get users cookies on server side before page is rendered. It works if I do it client side. But not with getInitialProps

**Comment by urmauur** [comment]
@maticzav hey guys, thanks for attention, but this problem already solve
