### ISSUE TITLE
Update token when user name updated

### ISSUE THREAD

**Issue by DiegoMcDipster** [maticzav/nookies#443]
Hi,

I'm pretty new to javascript and I'm working on a project with nextjs and firebase.  This question is standard functionality and I've already spent about 4 hours trying to figure it out.... so, i'm hoping someone here can help me out.

I set up firebase auth with email. The only issue I am facing is that the user.displayName is empty. So I created a simple update user profile form.  I do the update according to the firebase docs: https://firebase.google.com/docs/auth/web/manage-users#update_a_users_profile

However, since my getServerSideProps retrieves the user profile from the cookie the update is not reflected on my screen.

How do I update the cookie so that the whole application can see the updated user name?

Thanks in advance for your help!

```ts
export async function getServerSideProps(context) {
  try {
    const cookies = nookies.get(context);
    const token = await verifyIdToken(cookies.token);
    const { name, uid, email, email_verified } = token;

    return {
      props: {
        session: { name, email, uid, emailVerified: email_verified },
      },
    };
  } catch (error) {
    console.log("an error occured: ", error.message);
  }
}
```

And this is my AuthProvider

```ts
export const AuthProvider = ({ children }) => {
  firebaseClient();
  const [user, setUser] = useState(null);

  useEffect(() => {
    return firebase.auth().onIdTokenChanged(async (user) => {
      if (!user) {
        setUser(null);
        nookies.set(undefined, "token", "", { path: "/" });
        return;
      }
      const token = await user.getIdToken();
      setUser(user);
      nookies.set(undefined, "token", token, { path: "/" });
    });
  }, []);

  return (
    <AuthContext.Provider value={{ user }}>{children}</AuthContext.Provider>
  );
};
```

**Comment by Slowlydev** [comment]
Thats because u can't get the displayName of an user from the Token [here](https://firebase.google.com/docs/reference/admin/node/admin.auth.DecodedIdToken) u can see what u can get from verifyIdToken().
