### ISSUE TITLE
Detect cookie changes

### ISSUE THREAD

**Issue by Anam0927** [maticzav/nookies#464]
Hey!

More of a question than an issue... 
How do I detect when a certain cookie changes? 

Like for example, a user logs in one tab and logs out in another... Only the tab in which he logged out is reflecting the changes... How can I make it so that it reflects across tabs?

**Comment by EricLiuZero** [comment]
I got the same issue with you @Anam0927 , especially my project is based on Next.Js.
I need to handle users login states among some components for both SSR & CSR.
Then I found API doc as follows:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged
Hope it is helpful for you.
