### ISSUE TITLE
Only last cookie gets set when trying to set 2 cookies

### ISSUE THREAD

**Issue by RobertB4** [maticzav/nookies#5]
I use two cookies for user authentication and authorization in my app. I want to refresh both of them when the user loads a page. I noticed that my `cookie_one` does not get set on page load. Only the second one gets set. Is this a nookies bug (or possibly a bug of the cookie library that nookies uses internally) or am I missing something obvious?

```
static async getInitialProps(ctx: { req; res }) {
      if (parseCookies(ctx).cookie_one && parseCookies(ctx).cookie_two) {
        setCookie(ctx, 'cookie_one', parseCookies(ctx).cookie_one, {
          maxAge: 36000 * 24 * 14,
        });
        setCookie(ctx, 'cookie_two', parseCookies(ctx).cookie_two, {
          maxAge: 36000 * 24 * 14,
        });
      }

      return {};
    }
```

**Comment by bigorangemachine** [comment]
Hey @RobertB4 

I had this issue to; I created a PR (#14)
