### ISSUE TITLE
Any working example of this package as cookies consent banner?

### ISSUE THREAD

**Issue by kamal-choudhary** [maticzav/nookies#500]
Thanks for this useful package.

I have a static website in Next.js and I have two scripts in it i.e. Google Analytics 4 & TruConversion Heatmap.

Both of these scripts are implemented using the newest next/script component.

When the user loads my website, I want to show the cookies consent banner (with accept/reject button), if the user accepts then I want my scripts i.e. GA4/Heatmap to run otherwise don't run those scripts.

Has anyone implemented something like this using this package, I'll be very thankful if someone can share a code snippet OR just guide me in the right direction?

**Comment by nathanaelphilip** [comment]
@kamal-choudhary I’m not sure if you figured it out, but you could probably just use `useState` and `useEffect`; 
just set the initial state to `false`; then check for the existence of the cookie acceptance cookie; if none is set, display the modal – if it’s set to `false`, don’t load anything; if `true`, load the scripts.

**Comment by kamal-choudhary** [comment]
@nathanaelphilip thanks for replying to my question.

Actually, I have figured it out and used some other library.

And yes, the solution was very much similar to what you explained.
