### ISSUE TITLE
support for older browsers

### ISSUE THREAD

**Issue by mattisa** [maticzav/nookies#52]
Hi. 
Seems that typescript compilation target is set to "es6". 
This causes dist code to contain arrow function that will break IE11.

(https://caniuse.com/#feat=arrow-functions)

If compilation target would be "es5": 
- IE11 would work and there would be 
- uncompressed dist size would raise from 3611B to 4013B

Should i fork this for my own use or are there any plans to support older browsers while IE11 dies away?

**Comment by maticzav** [comment]
Hey @mattisa 👋,

Thanks for pointing this out. I changed the target to `es5` and added Uglify which should probably do the job with changing bundle sizes. The change should be up in a second.

**Comment by kateika** [comment]
If we start to talk about browser support: where I can find information about browsers that are supported by nookies?
Chrome, Firefox, IE10+, Edge, Safari?
