### ISSUE TITLE
How it should be used in client? 

### ISSUE THREAD

**Issue by SilentImp** [maticzav/nookies#58]
getInitialProps don't run on client side.
how I should use niikies to set cookies on client without ctx?

**Comment by maticzav** [comment]
@SilentImp just added the client usage section to README.

https://github.com/maticzav/nookies#cookies-on-the-client

Let me know whether this solves your problem. 🙂

**Comment by designbyadrian** [comment]
@maticzav The README doesn't explain how to set a cookie client-side, only how to get them. setCookies seem to require the NextJS context object.

**Comment by maticzav** [comment]
Yes, or an empty object. I would be very grateful if you could compose a PR to add this to README. Let me know if that would work for you 🙂
