### ISSUE TITLE
Add typehinting

### ISSUE THREAD

**Issue by dextermb** [maticzav/nookies#6]
I really like this small little package. Would be great if `get`, `set`, and `destroy` were typehinted!

**Comment by maticzav** [comment]
Hey @dextermb 👋,

what do you mean with `typehinting`?

**Comment by dextermb** [comment]
@maticzav can't say i've written a JavaScript library before, but when writing code it'd suggest methods and functions. Here's an example: https://strongloop.github.io/strongloop.com/strongblog/type-hinting-in-javascript/#jsdoc-annotations
