### ISSUE TITLE
Typings for typescript and issues with code

### ISSUE THREAD

**Issue by andreasbergqvist** [maticzav/nookies#9]
Hi

I've used your library in a Typescript project.

I have created a Pull Request for you library to DefinitelyTyped where Typescript typings can be created:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29857#pullrequestreview-166261594

When doing this I noticed a few things with the code:

1. The default value for ctx seems unnecessary in set cookie?
`export function setCookie(ctx = {}, name, value, options = {}) {`

2. Set cookie should not return anything?
Just remove `return {}`

I can fix in a Pull Request if you want me?

**Comment by maticzav** [comment]
Hey, thank you for being so patient. I would love to merge a PR with fixes! Let me know if you need any help whatsoever with the implementation 🙂
