### ISSUE TITLE
destroyCookie

### ISSUE THREAD

**Issue by lishine** [maticzav/nookies#97]
destroyCookie does not work in this situation, while nookies.set does the work
nookies on 2.06 version
```
import nookies, { destroyCookie } from 'nookies'

export const logout = async ({ res }) => {
    console.log('LOGOUTING')
    console.log('destroying cookie')
    // destroyCookie({ res }, 'sbsToken')
    nookies.set({ res }, 'sbsToken', '', {
        maxAge: -1,
        path: '/',
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
    })
    return { ok: true }
}
```

**Comment by creativiii** [comment]
Yeah I'm not sure what is going on, destroycookie and nookies.destroy only seem to work sometimes.
If I clear cache and cookies they'll work fine until the next time React is reloaded.

**Comment by x4080** [comment]
I tried it and it works correctly, on client side must use {}

```
destroyCookie({}, 'sbsToken')
```

**Comment by denny7** [comment]
I tried everything and nothing work for me on server side.

**Comment by ejoebstl** [comment]
It also seems like the path `/` is used when creating the cookie, but not when deleting it.

**Comment by maticzav** [comment]
@ejoebstl there's no default in the code that would define the path. Why do you think that's the case?

**Comment by ejoebstl** [comment]
@maticzav Looks like I was mistaken, there was a code path I was not aware of. Aplogies!

**Comment by blueshark226124** [comment]
When creating a cookie, I set the path as "/". And destroying it, also set the path as "/" so it works properly.

**Comment by KeitelDOG** [comment]
@blueshark226124  thanks. Setting the same `path` on `setCookie` and `destroyCookie` did solve it. I just tested it client side:

```js
setCookie(null, 'sbsToken', dataString, {
  maxAge: -1,
  path: '/',
  httpOnly: true,
  secure: process.env.NODE_ENV === 'production',
});
```

```js
destroyCookie(null, 'sbsToken', {
  path: '/', // THE KEY IS TO SET THE SAME PATH
})
```

 The `destroyCookie` function accept options parameter too

**Comment by moaaz-bhnas** [comment]
Tried everything here, and didn't work with me and had to use a simpler package: [next-cookies](https://github.com/matthewmueller/next-cookies)

**Comment by KeitelDOG** [comment]
> Tried everything here, and didn't work with me and had to use a simpler package: [next-cookies](https://github.com/matthewmueller/next-cookies)

Did you explicitly set the `path` in `destroyCookies()` to the same value of the cookie you want to delete? By default, when creating one, it uses `/`, but you can use any. And on deleting, by default, is uses no path, hence deleting no cookie, so you have to provide one

**Comment by Adarsh1999** [comment]
> I tried it and it works correctly, on client side must use {}
> 
> ```
> destroyCookie({}, 'sbsToken')
> ```

This thing is working for me.
`import { destroyCookie } from 'nookies';
destroyCookie({}, 'access');
`

This is the code if someone needs help

**Comment by moaaz-bhnas** [comment]
@KeitelDOG Sorry for late reply. I didn't have access to my laptop for few weeks.
Thank u for trying to help 🙏, but I forgot all about the issue 😄

**Comment by sharif51693** [comment]
You need to send a response back to the server after deleting the cookie:

```
destroyCookie({ res }, "auth", {
          path: "/",
        });

        res.send("Logged out");
```

**Comment by Radmehr-aghdam** [comment]
In server-side use this:
`nookies.destroy(req , 'cookie_name' , {path: '/'})`

**Comment by Miskoo995** [comment]
It didn't work for me, for setting the path or the first parametar as  {} object. Very poorly described in documentation, what you should even do on first place.

**Comment by tmoutinho** [comment]
It's working for me but it takes a long time to destroy. In my case I set the cookie on the server and tried to delete in the client.

`destroyCookie({}, 'MY_TOKEN', {
      path: '/',
    });`

**Comment by jeffminsungkim** [comment]
If anyone has been struggling with this issue in production, you should include a domain option as well.

```javascript
const options = {
  path: '/',
  domain: 'example.com',
}
nookies.destroy(context, COOKIE_NAME, options)
```

**Comment by ABIDULLAH786** [comment]
> destroyCookie does not work in this situation, while nookies.set does the work nookies on 2.06 version
> 
> ```
> import nookies, { destroyCookie } from 'nookies'
> 
> export const logout = async ({ res }) => {
>     console.log('LOGOUTING')
>     console.log('destroying cookie')
>     // destroyCookie({ res }, 'sbsToken')
>     nookies.set({ res }, 'sbsToken', '', {
>         maxAge: -1,
>         path: '/',
>         httpOnly: true,
>         secure: process.env.NODE_ENV === 'production',
>     })
>     return { ok: true }
> }
> ```

i had also ths same issue whenever i clicked the logout button even though it removed the cookies but it hang the web page so after exploring the issue then i came to know that  i was using router.replace("/login") and router.push("/login") but the solution is i have to use reouter.reload()


                     destroyCookie({}, 'user', { path: '/' });
                      destroyCookie({}, 'role', { path: '/' });
                      router.reload();

**Comment by BrunoMeirel3s** [comment]
> @blueshark226124 thanks. Setting the same `path` on `setCookie` and `destroyCookie` did solve it. I just tested it client side:
> 
> ```js
> setCookie(null, 'sbsToken', dataString, {
>   maxAge: -1,
>   path: '/',
>   httpOnly: true,
>   secure: process.env.NODE_ENV === 'production',
> });
> ```
> 
> ```js
> destroyCookie(null, 'sbsToken', {
>   path: '/', // THE KEY IS TO SET THE SAME PATH
> })
> ```
> 
> The `destroyCookie` function accept options parameter too

Thanks man, that worked for me :)

**Comment by JD-Rodrigues** [comment]
It worked for me too.
